### ISSUE TITLE
Investigate whether we can use edm:type

### ISSUE THREAD

**Issue by marlo-longley** [sul-dlss/nta-arclight#10]
Thanks to @ggeisler for researching this as a possibility
Investigate whether we can use edm:type as a high level media format facet
Do we have enough data?
Can we map the specific types automatically to edm:type? For example, "Film in a box" to "Video" when we are generating our final data formats

**Comment by laurensorensen** [comment]
Confirmed that all records have edm:type data associated. Does anyone have objections to changing VIDEO to Moving Image? Video isn't the original format and I'm inclined to use a more general term than film because don't want to repeat Format facet. 

I'm still investigating 3D and Images edm:type data. Some 3D have druids associated which were mis-labeled with H-XXXX numbers. Going through and fixing these one-by-one.

**Comment by ggeisler** [comment]
`Moving Image` seems fine to me. I'll update the mockup in #29 to reflect that.
