### ISSUE TITLE
Decide on asset pipeline strategy (does this have implications for generating the base app?)

### ISSUE THREAD

**Issue by marlo-longley** [sul-dlss/nta-arclight#12]

**Comment by marlo-longley** [comment]
For reference:
Arclight [depends on BL7,](https://github.com/projectblacklight/arclight/blob/747ae166338f542854e47b8e0a9af8250fac92bd/arclight.gemspec#L25) which uses Boostrap 4

**Comment by jcoyne** [comment]
@marlo-longley Blacklight 7 supports both Bootstrap 4 & 5. (See Argo as an example)

**Comment by jcoyne** [comment]
I wouldn't recommend webpacker, it's basically deprecated in Rails.. Esbuild is way easier, especially now that we don't need Babel for IE11.

**Comment by thatbudakguy** [comment]
I just tried a fresh rails app (on v7) with:
```
rails new . -j esbuild --css bootstrap
```
based on the docs for `jsbundling-rails` and `cssbundling-rails`, and it seemed to do exactly what I hoped: esbuild and bootstrap and its dependencies all got installed via yarn (instead of using gems), I got bootstrap v5 out of the box, and my generated `application.css` had bootstrap already compiled in. there was a sourcemap for the js generated too.

**Comment by marlo-longley** [comment]
Closed based on discussion
