### ISSUE TITLE
Determine rails features that won't be used and shouldn't be generated

### ISSUE THREAD

**Issue by marlo-longley** [sul-dlss/nta-arclight#15]

**Comment by jcoyne** [comment]
@marlo-longley which sort of files are you talking about?

**Comment by thatbudakguy** [comment]
@jcoyne we were talking about various rails libs that we may or may not need, that have content auto-generated (i.e. stuff like actioncable).

basically, which things on this list do we want to skip when doing `rails new`, since we know we won't use them for this app:
<html>
<body>


Argument | Description
-- | --
--skip-git | Skip git init, .gitignore, and .gitattributes
--skip-keeps | Skip source control .keep files
--skip-action-mailer | Skip Action Mailer files
--skip-action-mailbox | Skip Action Mailbox gem
--skip-action-text | Skip Action Text gem
--skip-active-record | Skip Active Record files
--skip-active-job | Skip Active Job
--skip-active-storage | Skip Active Storage files
--skip-action-cable | Skip Action Cable files
--skip-asset-pipeline | Skip Asset Pipeline
--skip-javascript | Skip JavaScript files
--skip-hotwire | Skip Hotwire integration
--skip-jbuilder | Skip jbuilder gem
--skip-test | Skip test files
--skip-system-test | Skip system test files
--skip-bootsnap | Skip bootsnap gem


</body>
</html>

**Comment by cbeer** [comment]
Unless we have a specific need, I'd suggest we just accept all the Rails defaults and just use the parts we need. Having e.g. actioncable but not using it doesn't seem actively harmful to me (or at least less surprising than expecting part of the default bundle but not having it)

**Comment by thatbudakguy** [comment]
can you say more about what things (other than ourselves) would expect that? my instinct would be to not add pieces we don't need, since we then install gems we don't use on every CI run, and their 2nd-order dependencies interact with the dependencies of things we do care about (maybe these assumptions are wrong?)

**Comment by jcoyne** [comment]
@thatbudakguy when you add `gem 'rails'` to your gemfile, it's already going to download all those gems. There isn't an easy way to prevent them from being installed.

**Comment by thatbudakguy** [comment]
ah, I didn't realize they were also dependencies of rails itself. thanks for explaining. if we can't easily get out of pulling them in, then we may as well keep the config as close to default as possible.

**Comment by marlo-longley** [comment]
We decided to go with the version in #14 -- closing.
