### ISSUE TITLE
Investigate assumptions about metadata that underly default box and item display

### ISSUE THREAD

**Issue by marlo-longley** [sul-dlss/nta-arclight#3]

**Comment by marlo-longley** [comment]
Currently our metadata is flattened on the item level:

https://docs.google.com/spreadsheets/d/1loytZIXYMuUajCkJRi3CyiqROMOARbhv/edit#gid=360187303

**Comment by marlo-longley** [comment]
Box > [Folder?] > Item

**Comment by laurensorensen** [comment]
**Summary of analysis:**
 
Column I has associated Box-level description, applies to Column A. Electrical transcription discs do not have a box number, only item-level but do have a "boxes" description in Column I which applies to all Electrical transcription discs.

Format (Column V) includes Folder as one value among many, including Film in can, Loose leaf photo album, Package, etc). Safe to say Column V describes next level down from Box (or level down from Day, if Electrical transcription discs), equivalent to EAD's "item".  

**More detailed analysis:** 

Column I (dc:description), in the spreadsheet inventory linked above has metadata associated with only the Box level (Box is in Column A). 
For example, Box 3, which includes folders H-0264 through H-0299 has the header text in Column I associated with page 33 of the [original IMT inventory](https://purl.stanford.edu/hj785rz1466), the header with info about Box 3. 
The exception to this pattern is the Electrical transcription discs which are only item level and do not have an individual box number associated with them. They do have metadata in that Column I as well, but for "Boxes" generally that contain discs, see row associated with H-5260_0698A_2 in spreadsheet for an example. 

Each "H-..." identifier is associated with the Format listed in Column V, mostly folders but sometimes Film in can, Volume of bound newspapers and others. Each of these H-... identifiers has a druid associated, so Column V appears to be the "item" in this context, since it will have a digitized item associated with it (with varying names of Folder, Film in can, Loose leaf photo album, Package, etc). 

In Column A, the Box number associated with each "H-..." identifier has been copied in from the original IMT inventory. The exception to this are the Electrical transcription discs which are item level; however, there is an [inventory of Electrical Transcription Discs in H-1218](https://exhibits.stanford.edu/virtual-tribunals/catalog/vc421jh1418). It appears this has been transcribed, however - e.g., Disc 79A (<-- in dc:description, Column G) "Mr. Alderman on aggressive war. Part 1" (<-- in dc:title Column D) appears in the spreadsheet metadata we received.

For the Electrical transcription discs, grouping by day (instead of box) would be the preferred way to display (there are about 20 discs per day), since this reflects original order and was discussed as preferred at the in-person NTA meeting at LDCY. Columns Q (day-date only) and Column U (appears to be range of time within the day when disc was recorded) would apply here.  

-

Inventory with Columns referred to above is here: https://docs.google.com/spreadsheets/d/1loytZIXYMuUajCkJRi3CyiqROMOARbhv/edit#gid=360187303

Original IMT inventory: https://purl.stanford.edu/hj785rz1466
